spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task_management_sys
    username: root
    password: jbw051201
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      # redis连接池最大连接数(使用负数表示没有显示，默认8)
      lettuce:
        pool:
          max-active: 8
          # 连接池最大阻塞等待时间(使用负值表示没有限制，默认-1)
          max-wait: -1
          # 连接池中的最大空闲连接 默认 8
          max-idle: 8
          # 连接池中的最小空闲连接 默认 0
          min-idle: 0
      password: jbw051201

#   Mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug